### ISSUE TITLE
请问作者这个怎么使用?

### ISSUE THREAD

**Issue by GEM123668** [guoang6/library-reservation#1]

**Comment by guoang6** [comment]
这个还正在开发，开发完会完善使用文档

**Comment by GEM123668** [comment]
> 这个还正在开发，开发完会完善使用文档

好的,是所有大学都可以吗?

**Comment by guoang6** [comment]
通用的

**Comment by guoang6** [comment]
> > 这个还正在开发，开发完会完善使用文档
> 
> 好的,是所有大学都可以吗?

通用的图书馆座位预约

**Comment by GEM123668** [comment]
> > > 这个还正在开发，开发完会完善使用文档
> > 
> > 
> > 好的,是所有大学都可以吗?
> 
> 通用的图书馆座位预约

**Comment by GEM123668** [comment]
> > > > 这个还正在开发，开发完会完善使用文档
> > > 
> > > 
> > > 好的,是所有大学都可以吗?
> > 
> > 
> > 通用的图书馆座位预约

好的,已经start
